email: ...
full_name: Daniel Mitchell
name: Daniel
background: Daniel is a creative and technically-skilled individual who uses this assistant for managing personal emails, scheduling, and day-to-day communication.
schedule_preferences: By default, unless specified otherwise, you should make meetings 30 minutes long.
background_preferences: |
  This email is for personal use. For anything related to work or business, Daniel will usually respond from a different address. Prioritise friends, family, important notifications, or anything related to appointments and personal interests.
response_preferences:
timezone: "Europe/London"
rewrite_preferences: |
  Daniel has a few preferences for how his emails are written:

  - Match the sender’s tone. If they’re formal, mirror it. If they’re casual, keep it friendly and relaxed.
  - Be direct and to the point with people Daniel knows well.
  - Avoid sounding robotic or like an assistant – write as if Daniel is replying himself.
  - Daniel usually skips greetings and sign-offs in casual conversations.

triage_no: |
  - Promotional emails and sales offers unless it's something Daniel has signed up for
  - Cold outreach from unknown services or vendors
  - Notifications from social media platforms or apps unless explicitly important
  - Calendar invites that have already been accepted or are clearly spam
  - Comment notifications on shared documents unless tagged or directly addressed

triage_notify: |
  - Emails about upcoming appointments, deliveries, or bookings
  - Important personal messages from friends or family
  - New messages from services Daniel frequently uses (e.g., banking, health, subscriptions)
  - Reminders for upcoming events or actions needed (e.g. renewals, deadlines)
  - Confirmation or action-required emails from trusted services (e.g. Docusign, NHS, Gov.uk)

triage_email: |
  - Personal messages where someone is clearly trying to get in touch
  - Emails that require Daniel to confirm something, click a link, or follow up
  - Anything regarding financial matters, identity verification, or account access
  - Messages from close contacts even if there is no explicit question – treat them as important
  - Introductions or invitations to events Daniel may be interested in
  - Any back-and-forth threads Daniel is actively participating in

memory: true